### ISSUE TITLE
Make year in footer 4 digits over 2

### ISSUE THREAD

**Issue by margueritefruge** [OpenDenton/opendenton.github.io#15]
Make 2016 instead of 16

**Comment by newswim** [comment]
🎉🎂🎉🎂🎉🎉🎉🎈🎈🎂🎉🎉🎂🎂🎈YAAYYYYYYYYYY 🎉 🎈 🎂 !!!!!!
🎉🎂🎉🎂🎉🎉🎂🎉🎂🎂🎉🎉🎉🎈🎈🎂🎉🎉🎂🎈🎉🎂🎈🎈 !!!!!!!!!

**Comment by newswim** [comment]
MAKE 16 2016 AGAIN
