### ISSUE TITLE
Pull in images from twitter

### ISSUE THREAD

**Issue by newswim** [OpenDenton/opendenton.github.io#7]
Here's one option, may want to find something that's more maintained. 

https://github.com/jfrazelle/hashtag-pull

**Comment by jessehamner** [comment]
Can we run PHP on the git repo we’re using?

**Comment by newswim** [comment]
Good point, we can't run any server-side processes in this format (unfortunately). We'll probably need to embed a little client-side REST service to fetch images and put them in a collection.
